version: 2

project_name: ping-pong

builds:
  - binary: ping-pong
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: ping-pong
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{- if .Arm }}v{{ .Arm }}{{ end }}"
    formats: tar.gz
    format_overrides:
      - goos: windows
        formats: zip
    files:
      - LICENSE

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

dockers_v2:
  - images:
      - "ghcr.io/lavery98/ping-pong"
    tags:
      - "latest"
      - "{{ .Tag }}"
    labels:
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.description": "Simple HTTP server that responds to /ping with pong. Useful for remote monitoring of endpoints"
      "org.opencontainers.image.source": "{{.GitURL}}"
      "org.opencontainers.image.url": "{{.GitURL}}"
      "org.opencontainers.image.documentation": "{{.GitURL}}"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
